import time
import json
import torch
import rasterio
import numpy as np
from sqlalchemy.orm import Session
from scipy.ndimage import label, find_objects

from db.db import SessionLocal
from db.models import Entrenamiento

def TraerDeMiniOEntrenamientos():
    db = SessionLocal()
    #No son todos, es solo los que no tengan error
    # Listo para entrenar 
    datos = db.query(Entrenamiento).filter(Entrenamiento.status == "Lista para entrenar..")
    db.commit()
    db.close()
    if datos is None: 
        print("no hay Tabla de entrenamiento o no hay datos")
        return 1
    lista = {x.nombre_imagen for x in datos}


    if len(lista) == 0:
        #no hay datos
        return 2 

    # si hay datos se trae desde minio 
    client = Minio(
            "localhost:9000",
            access_key=DB_MINIO_USER,
            secret_key=DB_MINIO_PASS,
            secure=False)
    for d in datos:
        client.fget_object(
                "train-inputs",
                f"escena_{d.id}.tif",
                f"tmp/dataset/inputs/escena_{d.id}.tif")
        print("Archivo de input {d.id} descargado")
    for d in datos:
        client.fget_object(
                "train-masks",
                f"escena_{d.id}.tif",
                f"tmp/dataset/masks/escena_{d.id}.tif")
        print("Archivo de mask {d.id} descargado")
    # Todo sin problemas 
    return 0 

def ConsultarNroDeEntrenamientos():
    db = SessionLocal()
    #No todos, es solo los que no tengan error
    # Listo para entrenar 
    datos = db.query(Entrenamiento).filter(Entrenamiento.status == "Lista para entrenar..")
    db.commit()
    db.close()

    if datos is None: 
        print("no hay Tabla de entrenamiento o no hay datos")
        return 1
    lista = {x.nombre_imagen for x in datos}


    if len(lista) == 0:
        #no hay datos
        return -1 
    # Todo sin problemas 
    return len(lista) 

def ConsultarModelosNroDeEntrenamiento(nro):
    db = SessionLocal()
    #Buscar Modelos en la DB
    #Se Busca el ultimo modelo disponible 
    #fire_model_ver_{nro_version}.pth 
    # 
    modelos = db.query(Modelos)
 
    db.commit()
    db.close()   
    if modelos is None: 
        print("No hay Modelos registrados en la DB")
        return 1

    if len(Modelos) >= 1:
        #Aca tengo que recortar nro del ultimo modelo 
        if nroEnDB <= nro:
            # se procede a modelar un nuevo modelo
            return 0
    # Algun problema  
    return -1 
def AlmacenarModelo(nombre):
    db = SessionLocal()
    nuevoModelo = Modelos(
        name=nombre
    )
    db.add(nuevoModelo)
    db.commit()
    db.close()
    client = Minio(
        "localhost:9000",
        access_key=os.getenv("DB_MINIO_USER"),
        secret_key=os.getenv("DB_MINIO_PASS"),
        secure=False
    )
    bucket_name = "modelos"
    if not client.bucket_exists(bucket_name):
        client.make_bucket(bucket_name)
        print("Bucket para los modelos creado")
    client.fput_object(
        "modelos",
        f"{nombre}.zip",
        f"tmp/modelos/{nombre}.zip"
    )
    print(f"Modelo {nombre} subido.")

# =========================
# 🔁 MODELADOR
# =========================


def run():
    while True:
        #Si hay un nro de entrenamientos multiplo de 10 
        nro = ConsultarNroDeEntrenamientos()
        multiplo_10 = (nro % 10) == 0
        if multiplo_10:
            #Se verifica la prescencia del mismo en la db
            estado = ConsultarModelosNroDeEntrenamiento(nro)
            if estado == 0: 
                #se procede a modelar un nuevo modelo
        #Sino , se pone en espera 5 segundos
        time.sleep(5)
if __name__ == "__main__":
    run()


# =========================
# 🔧 Modelado de Colab: 
# =========================
# -*- coding: utf-8 -*-
"""Intento_de_entrenamiento.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/ ya no estan aca 
"""

!pip install rasterio torch torchvision tqdm

from google.colab import drive
drive.mount('/content/drive/')

!apt-get install tree -y

!cp -r "/content/drive/MyDrive/2026_1/PICD/dataset" /content/
DATASET_ROOT = "/content/dataset"

#DATASET_ROOT = "/content/drive/MyDrive/2026_1/PICD/dataset"

import os
import numpy as np
import rasterio
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from tqdm import tqdm

class FireDataset(Dataset):
    def __init__(self, root):
        self.root = root

        # ✔ rutas correctas según tu Drive
        self.inputs_dir = os.path.join(root, "inputs")
        self.masks_dir = os.path.join(root, "masks")

        # ✔ lista de archivos (asume mismo nombre en inputs y masks)
        self.files = sorted(os.listdir(self.inputs_dir))

    def __len__(self):
        return len(self.files)

    def _load_tif(self, path):
        with rasterio.open(path) as src:
            return src.read().astype(np.float32)

    def __getitem__(self, idx):
        fname = self.files[idx]

        # ✔ paths correctos en Drive
        x_path = os.path.join(self.inputs_dir, fname)
        y_path = os.path.join(self.masks_dir, fname)

        x = self._load_tif(x_path)   # (25, H, W)
        y = self._load_tif(y_path)   # (1, H, W)

        # ✔ reshape temporal (5 tiempos × 5 variables)
        x = x.reshape(5, 5, x.shape[1], x.shape[2])

        # ✔ normalización estable
        x_min = x.min()
        x_max = x.max()
        x = (x - x_min) / (x_max - x_min + 1e-6)

        x = torch.tensor(x, dtype=torch.float32)
        y = torch.tensor(y, dtype=torch.float32)

        return x, y

DATASET_ROOT = "/content/drive/MyDrive/2026_1/PICD/dataset"

dataset = FireDataset(DATASET_ROOT)

class ConvBlock(nn.Module):
    def __init__(self, in_c, out_c):
        super().__init__()
        self.net = nn.Sequential(
            nn.Conv2d(in_c, out_c, 3, padding=1),
            nn.ReLU(),
            nn.Conv2d(out_c, out_c, 3, padding=1),
            nn.ReLU()
        )

    def forward(self, x):
        return self.net(x)


class TemporalFireNet(nn.Module):
    def __init__(self):
        super().__init__()

        self.encoder = ConvBlock(5, 32)
        self.lstm = nn.LSTM(input_size=32, hidden_size=64, batch_first=True)
        self.decoder = nn.Sequential(
            nn.Conv2d(64, 32, 3, padding=1),
            nn.ReLU(),
            nn.Conv2d(32, 1, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        # x: (B, T, C, H, W)
        B, T, C, H, W = x.shape

        feats = []

        for t in range(T):
            ft = self.encoder(x[:, t])   # (B, 32, H, W)
            ft = ft.mean(dim=[2,3])      # global pooling -> (B, 32)
            feats.append(ft)

        feats = torch.stack(feats, dim=1)  # (B, T, 32)

        out, _ = self.lstm(feats)          # (B, T, 64)

        last = out[:, -1]                  # (B, 64)

        # expand spatially
        last = last[:, :, None, None].expand(-1, -1, H, W)

        return self.decoder(last)

device = "cuda" if torch.cuda.is_available() else "cpu"

#dataset = FireDataset("/content/dataset")
loader = DataLoader(dataset, batch_size=2, shuffle=True)

model = TemporalFireNet().to(device)

criterion = nn.BCELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)

for epoch in range(10):
    model.train()
    total_loss = 0

    for x, y in tqdm(loader):
        x, y = x.to(device), y.to(device)

        pred = model(x)
        loss = criterion(pred, y)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    print(f"Epoch {epoch}: loss={total_loss/len(loader):.4f}")

import torch
import torch.nn as nn
from torch.utils.data import DataLoader
from tqdm import tqdm

device = "cuda" if torch.cuda.is_available() else "cpu"

loader = DataLoader(dataset, batch_size=2, shuffle=True)

model = TemporalFireNet().to(device)

criterion = nn.BCELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)

# 🔥 control de entrenamiento
epoch = 0
#max_epochs = 50  # seguridad anti-loop infinito
max_epochs = 5  #seguridad anti-loop infinito, antes eran 50, ahora son 5, debido a 
#recorte en tiempo, el objetivo es tener un modelo rapido y no uno cientificamente 
#preciso, debido a que es una demostracion de automatizacion y para la presentacion
#del mismo solo 10 minutos y una cafetera con  systemd+linux
best_loss = float("inf")
patience = 2
no_improve = 0

while epoch < max_epochs:

    model.train()
    total_loss = 0

    for x, y in tqdm(loader):
        x, y = x.to(device), y.to(device)

        pred = model(x)
        loss = criterion(pred, y)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    avg_loss = total_loss / len(loader)
    print(f"Epoch {epoch}: loss={avg_loss:.6f}")

    # 💾 CHECKPOINT SIEMPRE
    torch.save(model.state_dict(),
               f"/content/drive/MyDrive/2026_1/PICD/fire_model_epoch_{epoch}.pth")

    # 💾 BEST MODEL
    if avg_loss < best_loss:
        best_loss = avg_loss
        no_improve = 0

        torch.save(model.state_dict(),
                   "/content/drive/MyDrive/2026_1/PICD/fire_model_best.pth")
    else:
        no_improve += 1

    # 🛑 EARLY STOP por estancamiento o loss ~0
    if avg_loss < 1e-6:
        print("🛑 Early stop: loss ~ 0 (posible colapso o convergencia)")
        break

    if no_improve >= patience:
        print("🛑 Early stop: sin mejora")
        break

    epoch += 1

model.eval()

x, y = dataset[0]
x = x.unsqueeze(0).to(device)

with torch.no_grad():
    pred = model(x)

pred = pred.cpu().numpy()[0,0]
print(pred.shape)
print(pred.min(), pred.max())

torch.save(model.state_dict(), "/content/drive/MyDrive/2026_1/PICD/fire_model.pth")

