version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - "8000:8000"
    #healthcheck:
      #test: ["CMD","curl", "-f", "http://localhost:8000/docs"]
      #interval: 5s
      #timeout: 5s
      #retries: 10
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DATABASE_URL=${DATABASE_URL}
    # Montamos el código fuente para Hot Reload
    volumes:
      - ./api/app:/app/app
    # Lanzamos la API con --reload
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped
  validador:
    build:
      context: .
      dockerfile: ./validador/Dockerfile
    command: python -u -m app.validador
    depends_on:
      db:
        condition: service_healthy
          #api:
        #condition: service_healthy

    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DATABASE_URL=${DATABASE_URL}
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: ./worker/Dockerfile
    command: python -u -m app.worker
    depends_on:
      db:
        condition: service_healthy
          #api:
          #condition: service_healthy

    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DATABASE_URL=${DATABASE_URL}
      - DB_MINIO_USER=${DB_MINIO_USER}
      - DB_MINIO_PASS=${DB_MINIO_PASS}
    volumes:                           # 
      - ./data:/app/data               # 
      - ./descargas:/app/descargas     # 
      - ./ordenes:/app/ordenes     # 
    restart: unless-stopped
  entrenador:
    build:
      context: .
      dockerfile: ./entrenador/Dockerfile
    command: python -m app.entrenador
    depends_on:
      db:
        condition: service_healthy
          #api:
          #condition: service_healthy

    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DATABASE_URL=${DATABASE_URL}
      - DB_MINIO_USER=${DB_MINIO_USER}
      - DB_MINIO_PASS=${DB_MINIO_PASS}
    volumes:                           # 
      - ./dataset:/app/dataset     # 
    restart: unless-stopped
  analista:
    build:
      context: .
      dockerfile: ./analista/Dockerfile
    command: python -u -m app.analista
    depends_on:
      db:
        condition: service_healthy
          #api:
        #condition: service_healthy

    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DATABASE_URL=${DATABASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped

  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000" # API S3
      - "9001:9001" # Panel web
    environment:
      MINIO_ROOT_USER: ${DB_MINIO_USER}
      MINIO_ROOT_PASSWORD: ${DB_MINIO_PASS}
    volumes:
      - minio_data:/data
  modelador:
    build:
      context: .
      dockerfile: ./modelador/Dockerfile
    command: python -u -m app.modelador
    depends_on:
      db:
        condition: service_healthy
          #api:
          #condition: service_healthy
      minio:
        condition: service_started
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DATABASE_URL=${DATABASE_URL}

      - DB_MINIO_USER=${DB_MINIO_USER}
      - DB_MINIO_PASS=${DB_MINIO_PASS}
    volumes:
      - ./tmp:/app/tmp
    restart: unless-stopped
  predictor:
    build:
      context: .
      dockerfile: ./predictor/Dockerfile
    command: python -u -m app.predictor
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DATABASE_URL=${DATABASE_URL}

      - DB_MINIO_USER=${DB_MINIO_USER}
      - DB_MINIO_PASS=${DB_MINIO_PASS}

    restart: unless-stopped



volumes:
  minio_data:
  postgres_data:
